### ISSUE TITLE
Link to Make Your First 2D Game with Godot playlist (Learn Godot: Beginner Edition)

### ISSUE THREAD

**Issue by razcore-art** [GDQuest/GDquest-website#102]
We should have a link to `Make Your First 2D Game with Godot` **playlist** now that the 2nd video is out. In Learn Godot: Beginner Edition we link to the 1st video of the project.

**Comment by NathanLovato** [comment]
There it is: https://www.youtube.com/playlist?list=PLhqJJNjsQ7KH_z21S_XeXD3Ht3WnSqW97
