### ISSUE TITLE
There's no need for a partial for power sequencer

### ISSUE THREAD

**Issue by razcore-art** [GDQuest/GDquest-website#120]
I'd remove the `layouts/partials/shortcuts.html` entry as it doesn't make sense. It's only used in one file - the power sequencer related shortcode. This should instead be the shortcode file directly.

**Comment by NathanLovato** [comment]
Agreed. I wonder if we can't directly use the go template code in the content now, actually. But you can move the logic to the shortcode.

**Comment by razcore-art** [comment]
I'm not sure what you mean by "`go` template code", do you mean `hugo` templates, as in `layouts/index.html`? If so, no it doesn't make sense to use the templates either, because you'd basically create a one-time-use template as this power sequencer stuff is related to one file only. The idea with templates is to use them over multiple files, but this isn't the case here.

Moving the contents of `layouts/partials/shortcuts.html` to `shortcodes/shortcuts_power_sequencer.html` is all that's needed.

**Comment by NathanLovato** [comment]
>  you mean hugo templates, as in layouts/index.html

Anything like `{{ . }}` is a go template. What I'm saying is that it may work if you move the content of `layouts/partials/shortcuts.html` to the markdown page directly, maybe not. I know it was in discussion at some point, dunno if it became an actual feature.

**Comment by razcore-art** [comment]
Alright. I think we might be using terminology differently. Templates for me are the files. this `{{ . }}` thing is called "the context" as far as I can tell which makes perfect sense, and is used *inside* the template files. I was confused cause I would have never thought about `{{ . }}` as the actual template since I haven't used `hugo` before so I lack in the terminology part. But their docs also refer to it as context so... anyhow, as long as we discuss about the same thing, that's fine.
![image](https://user-images.githubusercontent.com/1177508/70375029-17e90e80-1902-11ea-87c9-12271749eff5.png)

About the `shortcuts.html`, looking quickly at the docs, `hugo` guys recommend to have complex `html` stuff inside the `shortcode`s, as far as I can tell this is one usage for them so not to clutter the markdown file. Now in our case the `shortcode` is itself the entire contents of the file, but I think that's fine. Just put it in `shortcodes/shortcuts_power_sequencer.html`. Should I go ahead and do this?

**Comment by NathanLovato** [comment]
Everything in double brackets, `{{}}` is a go template. These languages you use in conjunction with html are called templating languages. This one is called go templates.

Sure, go ahead.
