### ISSUE TITLE
TOC doesn't get generated using hugo-theme-learn

### ISSUE THREAD

**Issue by razcore-art** [GDQuest/GDquest-website#121]

**Comment by razcore-art** [comment]
This happens because that functionality is in `hugo-theme-learn/layouts/partials/footer.html` and we're overwriting it with our own `layouts/partials/footer.html`

**Comment by NathanLovato** [comment]
You can do something like renaming `layouts/partials/footer.html` to `layouts/partials/footer_default.html`?

**Comment by razcore-art** [comment]
No, we'll rename to `custom-footer.html` this way it's used by hugo-theme-learn too. They have 3 `custom-` files to be replaced by us:
![image](https://user-images.githubusercontent.com/1177508/70376127-4a006d80-190e-11ea-97a3-1f01e1c37698.png)

**Comment by NathanLovato** [comment]
Okay all good!
