### ISSUE TITLE
Add vector arrow bg in the header

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/GDquest-website#17]
tiling pattern

**Comment by Tornadowarnung** [comment]
I'd love to try getting started with this issue. I don't quite understand what you mean with the title and description though. Could you elaborate?

**Comment by NathanLovato** [comment]
Sorry, I wrote the issue for myself, not thinking someone would ever offer to contribute it. This task is about adding tiling arrows as in the youtube banner's background:
 
![image](https://user-images.githubusercontent.com/12694995/50283273-b6cdee00-0498-11e9-85cc-72fa85cc9e33.png)

**Comment by Tornadowarnung** [comment]
Oof, I see what this issue is about now. After messing a bit with hugo and the source code I'm not quite sure anymore that I'll be able to actually do this issue. Sorry for getting your hopes up there.
