### ISSUE TITLE
Won't build in hugo > 0.35

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/GDquest-website#36]
Hey @djrm, since your changes to the website there are build errors with the posts' front matter. It started with commit c96182af3f164a4d4e6970d81155a8b7e45e41e2

The issue is now build errors like these stop the server, and I can't fix the issue. It still happens if I convert the data to toml or json, if I remove all calls to .Params.banner in the layouts... I looked at the commit's changes and I can't figure out why it happens. I didn't mind as the site previewed and built okay but now it's becoming an issue. Could you give me a hand on this one?

I also posted on the hugo forums: https://discourse.gohugo.io/t/nested-yaml-params-in-front-matter-crash-builds-since-0-40/11749/6

**Comment by djrm** [comment]
@NathanLovato alright i managed to solve the problem, will create a PR soon.

**Comment by NathanLovato** [comment]
Ah that was due to a taxonomy! I didn't use them much in the past tbh. Thanks :)
