### ISSUE TITLE
Parse the README from Power Sequencer and put it in the docs with getJSON

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/GDquest-website#50]
Just moved the data to a JSON file: https://github.com/GDquest/Blender-power-sequencer/blob/master/utils/shortcuts.json

Right now the make readme script on the Power Sequencer repo turns this data into an HTML table. Here's the result: https://github.com/GDquest/Blender-power-sequencer/#operators

**Comment by djrm** [comment]
the link to the json seems to be down.

**Comment by NathanLovato** [comment]
Fixed, I think I had lost the file merging branches

**Comment by djrm** [comment]
fixed by 53b0076ae80de30b127d0e49529aa94d96547855
