### ISSUE TITLE
Fixed left-column menu for Power Sequencer's Docs

### ISSUE THREAD

**Issue by aditiapratama** [GDquest/GDquest-website#68]
For this purpose I found the list of operators in left side is quite a lot. Do you think make categorize or parent/sub-menu will work?

This issue reference to https://github.com/GDquest/Blender-power-sequencer/issues/267

**Comment by NathanLovato** [comment]
There is a lot of operators indeed. I'd say first let's just focus on having a fixed left column, and think about categories later: hugo generates the page from a JSON file in power sequencer, so to create these categories we have to change the addon's source code as well.

**Comment by NathanLovato** [comment]
And thanks for offering your help :)

**Comment by aditiapratama** [comment]
Hi @NathanLovato can you guide me on `css` modification for this website. Currently I'm having difficulties find out where it should be, I create new modules in `resources > scss > modules`, and then import it in `gdquest.scss`, I do that when the hugo server is active, it read my modification but the change not implemented.

Thank you.

**Comment by NathanLovato** [comment]
That's how you do it, hugo rebuilds css automatically. Did you install hugo extended? the normal hugo package/executable doesn't support scss. Did you use the class you added on the website? It's working no problem here.

**Comment by aditiapratama** [comment]
Yes, I'm using Hugo extended, everything running fine for deploying on local, but when I update the `css`, nothing changed. 

Here's the structure modification I made,

![image](https://user-images.githubusercontent.com/982553/48115289-01066180-e295-11e8-987e-f060e2b130a9.png)

**Comment by NathanLovato** [comment]
It's weird, it's working here. If I add scss code or change css classes it rebuilds no problem
