### ISSUE TITLE
Build error: Cannot retrieve linked file in shortcut

### ISSUE THREAD

**Issue by Tornadowarnung** [GDquest/GDquest-website#74]
## Expected Behavior
Hugo should build the website normally

## Current Behavior
The build fails because the resource in `/content/blender/power-sequencer/docs/index.md:10:1` contains a broken link as a shortcut.

## Possible Solution
Correct or remove the link in `/content/blender/power-sequencer/docs/index.md:10:1`

## Steps to Reproduce
1. Pull the current master
2. Call `hugo` or `hugo server`

## Environment
Ubuntu 18.04 LTS, Hugo v0.52

## Detailed Error Message
```
Error: Error building site: "/home/xayah/dev/private/gdquest-website/content/blender/power-sequencer/docs/index.md:10:1": failed to render shortcode "shortcuts": failed to process shortcode: "/home/xayah/dev/private/gdquest-website/layouts/shortcodes/shortcuts.html:2:8": execute of template failed: template: shortcodes/shortcuts.html:1:3: executing "shortcodes/shortcuts.html" at <partial "shortcuts.h...>: error calling partial: "/home/xayah/dev/private/gdquest-website/layouts/partials/shortcuts.html:2:8": execute of template failed: template: partials/shortcuts.html:2:8: executing "partials/shortcuts.html" at <getJSON .>: error calling getJSON: failed to get getJSON resource "https://raw.githubusercontent.com/GDquest/Blender-power-sequencer/master/utils/shortcuts_docs.json": Failed to retrieve remote file: Not Found
```

**Comment by NathanLovato** [comment]
Just comment out the line or set this page to draft for now, see #70

**Comment by Tornadowarnung** [comment]
Ah, I didn't find #70 browsing though the other issues. Thanks for the hint!
