### ISSUE TITLE
Improve the shortcuts template styles

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/GDquest-website#88]
The [power sequencer docs](https://www.gdquest.com/blender/power-sequencer/docs/) aren't too pleasing to the eye right now. We could use some nicer styles to:

- Have a sticky sidebar on the left so you can always jump to different features' docs when browsing, see #68
- Have a card for each docs entry with a clean layout, see below

![Screenshot from 2019-08-31 23-48-46](https://user-images.githubusercontent.com/12694995/64069495-7b500a00-cc4a-11e9-856c-5c7840b5309d.png)

**Comment by EEP-Benny** [comment]
A card for each entry is a good idea. Maybe a divider between entries would be enough?

Are you sure about the subcaptions ("DESCRIPTION", "SHORTCUTS")?
In my opinion, they only add visual clutter, but don't help much (I can guess that the bordered `T` is a shortcut).

As in your image, we should change the shortcuts list (with space divided 50/50 into keys and description) into a table, where the keys use the space they need.
In Discord, you suggested striped rows for those shortcut tables. This may improve readability for longer tables, but if there is only one or two shortcuts, it may confuse more than help (_"Why is this shortcut highlighted?"_).

**Comment by NathanLovato** [comment]
Feel free to experiment with the style. I suggested cards because the styles exist, they're easy to add. But I don't know exactly how the docs would best look. There's just the menu bar on the left that should follow the user scrolling down the page. it's inconvenient right now. Also, the content box is a bit narrow. But that's about it.

> Are you sure about the subcaptions ("DESCRIPTION", "SHORTCUTS")?

No, but I can't assume that people will get everything at a glance. The captions can be smaller and with a lighter color. It's mostly for visual structure.

> In Discord, you suggested striped rows for those shortcut tables

Agreed, for less than 3 shortcuts, that is most of the entries, it's not helpful. So no need to add it for now

**Comment by EEP-Benny** [comment]
I found the HTML code for the page at `layouts\partials\shortcuts.html`, and the CSS code at `resources\scss\modules\_shortcuts.scss`. If I edit the HTML code and restart the hugo server, I can see the changes in the browser. However, changes in the scss file are ignored. Did I edit the wrong file, or is there some cache that I could delete?

Do you have an opinion about how much the code is allowed to change? I would like to change the shortcut list from something like
```html
<div class="shortcut">
  <div>
    <span class="keystroke"><code>Alt</code><code>↑</code></span>
    <span>Move to Open Channel Above</span>
  </div>
</div>
<div class="shortcut">
  <div>
    <span class="keystroke"><code>Alt</code> <code>↓</code></span>
    <span>Move to Open Channel Below</span>
  </div>
</div>
```
to 
```html
<dl class="shortcutlist">
  <dt><kbd>Alt</kbd> <kbd>↑</kbd></dt>
  <dd>Move to Open Channel Above</dd>
  <dt><kbd>Alt</kbd> <kbd>↓</kbd></dt>
  <dd>Move to Open Channel Below</dd>
</dl>
```
I feel that a "definition list" is (kind of) the right thing here. Also, there is a html element for keyboard input: `kbd`.
Any opinions/suggestions on that?

We can format the definition list in the "old way" using a css grid. This also helps fixing the spacing between keys and description.

**Comment by NathanLovato** [comment]
> Do you have an opinion about how much the code is allowed to change?

As much as you want!

>  If I edit the HTML code and restart the hugo server, I can see the changes in the browser. However, changes in the scss file are ignored.

You almost never need to restart the server, hugo rebuilds and reloads modified files automatically. 
Did you install npm dev dependencies? I think you still need e.g. postcss-cli separately from hugo to build scss? `npm install` should sort things out.

>I feel that a "definition list" is (kind of) the right thing here.

It's not a list of definitions though. Why not use a table?

**Comment by EEP-Benny** [comment]
`npm install` did the trick! I wasn't aware that hugo uses npm packages.
Now scss is compiled, and auto reload also works.

> It's not a list of definitions though. Why not use a table?
Well, you could say that it "defines" the action of each keyboard shortcut. 

With a table, I didn't find a way to say: "Make the first column as wide as its content, and use the remaining space for the second column". With a css grid, I can do this via
```css
grid-template-columns: max-content auto;
```
But I will look again if there is a simple solution using tables.

**Comment by NathanLovato** [comment]
You can use flexbox with `align-items: flex-start` on a container to make elements use the width of the content, otherwise I think with table columns should be the size of the biggest cell's content (+ padding)?

**Comment by NathanLovato** [comment]
I think the issue you're having is we don't have style resets on the website. We could use something like https://github.com/jgthms/minireset.css/blob/master/minireset.css to have a sane base to build upon

**Comment by EEP-Benny** [comment]
I'm not sure what `align-items` would help. Yes, you can use flexbox to "fit to content". But this works per element. If the shortcuts have different length, it looks like this:
> ![grafik](https://user-images.githubusercontent.com/9270901/64076934-67002180-cccb-11e9-9f87-10ae2b07e3ad.png)


With a table, I get this (the keyboard shortcuts get squished together, if the text is too wide):
> ![grafik](https://user-images.githubusercontent.com/9270901/64077131-88620d00-cccd-11e9-97df-ce89b7a8d2dc.png)

What we (probably) want is the following, which is possible with CSS grids:
> ![grafik](https://user-images.githubusercontent.com/9270901/64076945-9151df00-cccb-11e9-84c5-b106a8409284.png)

(Here, I also changed the font of the keys. It looks better this way, and uses a little less space)

Update: I managed to get the same look (as in the last image) with a table, by setting the first column to
```css
    width: 0;
    white-space: nowrap;
```
This forbids line breaks, and stretches the column just wide enough to fit the longest keyboard shortcut.

**Comment by NathanLovato** [comment]
Nice 🙂

> I'm not sure what align-items would help. Yes, you can use flexbox to "fit to content". But this works per element.

True, I had forgotten about that. I don't write css often 😄

**Comment by EEP-Benny** [comment]
Is the expected procedure like this? I fork this repository, commit my changes into a new branch, and create a pull request here?

--- 

Regarding the sticky sidebar:
A full-height sidebar like in the [blender docs](https://docs.blender.org/api/blender2.8/) is easy (with `position: fixed`), but doesn't fit the current page layout.
I would prefer something like this:
![grafik](https://user-images.githubusercontent.com/9270901/64115486-16063100-cd90-11e9-989c-b46505d0f115.png)
The sidebar starts at the current position, but sticks to the top of the screen when scrolling down (using `position: sticky`).
For this to work, I have to remove the css grids that are currently used for the page layout. I don't think they are necessary for this individual page, but I'm not sure how this would affect other pages.

**Comment by NathanLovato** [comment]
> I fork this repository, commit my changes into a new branch, and create a pull request here?

Yes!

> Regarding the sticky sidebar

Agreed, yours look nice

> For this to work, I have to remove the css grids that are currently used for the page layout

If it's in partial/shortcuts.html no problem. This is a partial used inside a broader layout. The files that affect the rest of the website are things like baseof.html, default.html etc. in the layout folders

**Comment by EEP-Benny** [comment]
> For this to work, I have to remove the css grids that are currently used for the page layout

I have to change this statement: It's not the (global) grid, but 
```css
main {
    overflow: auto;
}
```
that prevents stickyness.
May I remove this line, or will this have unintended consequences somewhere else?

Also, can you help me with increasing the content width? I didn't find the "right spot" to make the content wider.
