### ISSUE TITLE
Broken codeacademy link in become a game developer post

### ISSUE THREAD

**Issue by razcore-art** [GDquest/GDquest-website#97]
It's probably an old link to a removed place on the codeacademy website in the [Become a game developer post](https://www.gdquest.com/tutorial/game-design/godot/become-a-game-creator/first-steps-programming/) under CODECADEMY’S INTERACTIVE PYTHON 3 TRACK sub-chapter. I could find only a Python 2 free course, the others need membership.

**I don't recommend anyone learn Python 2 any more so this section should probably be removed if there's no other free Python 3 alternative.**

**Comment by NathanLovato** [comment]
Good to know. There's this one as an alternative, but I'm not sure about the quality of the content: https://www.learnpython.org/

**Comment by razcore-art** [comment]
I don't know this site either, I'll have to review it.

**Comment by razcore-art** [comment]
I checked it out, it goes quite fast over the concepts and python language itself. I personally don't think it's a very good beginner resource, it looks very superficial and you don't get a sense of what can be done with Python. At the end of it I don't expect anyone to be left with anything else than just a sense of "Python has these language features that I have no idea how to use in practice"

**Comment by razcore-art** [comment]
This isn't an interactive course/book, and although it might be a bit too much to start off with, I still think it's a better fit for anyone wanting to see what Python can do (with some of the core modules): https://diveinto.org/python3/table-of-contents.html. Has lots of examples and exercises that give you a real feel for what the language can do.

Couple this with [pythonds](https://runestone.academy/runestone/books/published/pythonds/index.html) and it's good imperative-programming language starting point for people considering serious programming (that's needed at the level of game dev.)

**Comment by NathanLovato** [comment]
We're targetting people who have no experience and want to make games, not necessarily become professional developers. A game designer can get by with limited programming skills for instance. Even if I'd also recommend brushing your general coding skills in parallel to gamedev.

**Comment by razcore-art** [comment]
Sure, but I think the main point against learnpython.org is that it doesn't leave beginners with anything of value because you don't see the concepts put in practice. It just goes through the programming language list of features.

I'm not advocating necessarily for dive into python, I just don't know a better (less detailed) resource
